from master import *
pixel_state.fill((255, 0, 0, 0))
pixel_state.show()
time.sleep(1)
pixel_state.fill((0, 255, 0, 0))
pixel_state.show()
time.sleep(1)
pixel_state.fill((0, 0, 255, 0))
pixel_state.show()
time.sleep(1)
pixel_state.fill((0, 0, 0, 255))
pixel_state.show()
time.sleep(1)
pixel_state.fill((0, 0, 0, 0))
pixel_state.show()
